### ISSUE TITLE
Pandas Error runpreprocess.py

### ISSUE THREAD

**Issue by ahmetgurhan** [wqi/WIMP#2]
Hello! 
First of all, thank you for making your code available for the readers of your great paper.
I am having an issue while running run_preprocess.py. I think while reading the csv something goes wrong since my error is a pandas error. When I try to run the script, it gives me:
KeyError: 'CITY_NAME'
When I go to the script and give "MIA" as the CITY_NAME, just to see what happens, I receive a similar error:
KeyError: 'OBJECT_TYPE'
I checked the paths for the data. It seems fine. What could be the reason?
Thank you!

**Comment by XM-WANG** [comment]
I met the same problem. Is there any solutions?

**Comment by XM-WANG** [comment]
I got the answer. The folder contains a file `Argoverse-Terms_of_Use.txt`. The code process all files rather than all csv files, so that leads to the error.
